services:
  mongo:
    image: mongo:7
    container_name: turbo-mongo
    ports:
      - '27017:27017'
    volumes:
      - turbo-mongo-data:/data/db
    restart: unless-stopped

volumes:
  turbo-mongo-data:
